### ISSUE TITLE
Herd Feedback

### ISSUE THREAD

**Issue by natepill** [kevin-meyers/vaccine-inc#1]
I can’t run anything of your files. **The program is not parsing any command-line arguments**. I get the following terminal error:

vaccine-inc git:(master) python3 simulation.py 100 0.00 Ebola 1.00 0.00 10
Traceback (most recent call last):
  File "simulation.py", line 166, in <module>
    e_sim.sim_start()
  File "simulation.py", line 120, in sim_start
    with open(self.file_name, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/sim-log-10-13-2019.17:13:24'

**Comment by kevin-meyers** [comment]
Hey nate we are fixing it right now, thanks for the notice

**Comment by colo6299** [comment]
Fixed.
